<a href="https://colab.research.google.com/github/mohammad-bornosi/MME/blob/master/3/3.2%20Symmetric%2C_Positive_Definite_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Symmetric, Positive Definite Matrices
The LU decomposition of a symmetric, positive definite matrix A can always be
computed without pivoting.
LU decomposition fails when digonal entry after adding gussian elimination become zero can handle by pivoting but in symmetric, positive definite matrices digonal entry is more that zero

https://www.youtube.com/watch?v=-WgyyxziBz8 

In addition, it is possible to take advantage of symmetry so that the decomposition becomes symmetric, too, and requires half as much
work as in the general case.


Theorem 3.3 (LDLT decomposition). Any symmetric, positive definite matrix
A has a decomposition

A = LDLT ,

where L is lower triangular with ones on the main diagonal and D is a diagonal
matrix with positive diagonal elements.


The diagonal elements in D are positive, and therefore we can put:

![alt text](https://drive.google.com/uc?id=1BaLATvzV-6MWrkk8JZKMpcTcbhge_18_)

and then we get:

![alt text](https://drive.google.com/uc?id=1-3PowO6XHPaFJ9Po5pe5bifxz0Yw7_6A)

where U is an upper triangular matrix. This variant of the LDLT decomposition is
called the Cholesky decomposition.



In [2]:
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

A = scipy.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
L = scipy.linalg.cholesky(A, lower=True)
U = scipy.linalg.cholesky(A, lower=False)

print("A:")
pprint.pprint(A)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 6,  3,  4,  8],
       [ 3,  6,  5,  1],
       [ 4,  5, 10,  7],
       [ 8,  1,  7, 25]])
L:
array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])
U:
array([[ 2.44948974,  1.22474487,  1.63299316,  3.26598632],
       [ 0.        ,  2.12132034,  1.41421356, -1.41421356],
       [ 0.        ,  0.        ,  2.30940108,  1.58771324],
       [ 0.        ,  0.        ,  0.        ,  3.13249102]])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  """
