<a href="https://colab.research.google.com/github/mohammad-bornosi/MME/blob/master/3/3.5%20Banded_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Banded Matrices

If the nonzero elements are concentrated around the main diagonal, then
the matrix is called a band matrix.

matrix A is said to be a band
matrix if there are natural numbers p and q such that:

![alt text](https://drive.google.com/uc?id=1d1O2Cxxv6WLF8cVD3xdq_IXJZtv_UOdh)

w = q + p + 1 is called the bandwidth of the matrix. From the example, we see that w is the maximal number of nonzero elements in any row of A

We first consider the case p = q = 1. Such a band matrix is called 
tridiagonal.

![alt text](https://drive.google.com/uc?id=1-1C25GqxN8gCWIlecQM47PmKFI_Zy1r8)

The matrix can be stored in three vectors. In the solution of a tridiagonal system(thomas algorithm)Ax = b

 it is easy to utilize the structure

# Tridiagonal Matrices: Thomas Algorithm:

http://www.industrial-maths.com/ms6021_thomas.pdf

in my opinion: LU decomposition that described by above link L cumpute by  adding coefficients of rows in matrix L, and U is THE final matrix that we cumpute by gussian elimination described in linked above but the
diffrence is we dont need to change main diogonal elements to 1 by deviding  you can imagine thomas algorithm in this way:

![alt text](https://drive.google.com/uc?id=1-1ebgrk2MbLx4X6BE49AZ1waumVl56Iw)


In Gaussian elimination with partial pivoting, the band width of the uppertriangular matrix increases. If A has band width w = q + p +1(q diagonals under the main diagonal and p over), then, with partial pivoting, the factor U will have band width wU = p + q + 1.

It is easy to see that no new nonzero elements will be created in L

In [5]:
#The factors L and U in the LU decomposition of a band matrix A are band matrices.
import scipy.linalg as LA
import numpy as np
from pprint import pprint
A = np.array([
    [2,1,0,0],
    [-1,2,1,0],
    [0,-1,2,1],
    [0,0,-1,2]
])
P, L, U = LA.lu(A)

print("P:")
pprint(P)

print("L")
pprint(L)

print("U:")
pprint(U)

P:
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
L
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [-0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.        , -0.4       ,  1.        ,  0.        ],
       [ 0.        ,  0.        , -0.41666667,  1.        ]])
U:
array([[2.        , 1.        , 0.        , 0.        ],
       [0.        , 2.5       , 1.        , 0.        ],
       [0.        , 0.        , 2.4       , 1.        ],
       [0.        , 0.        , 0.        , 2.41666667]])


In Gaussian elimination with partial pivoting, the band width of the uppertriangular matrix increases. If A has band width w = q + p +1(q diagonals under the main diagonal and p over), then, with partial pivoting, the factor U will have
band width wU = p + q + 1. It is easy to see that no new nonzero elements will be
created in L

# inverse of Tridiagonal Matrices:
the inverse of a band matrix is usually a dense matrix.
Therefore, in most cases the inverse of a band matrix should not be computed

In [6]:
from numpy.linalg import inv
inv(A)

array([[ 0.4137931 , -0.17241379,  0.06896552, -0.03448276],
       [ 0.17241379,  0.34482759, -0.13793103,  0.06896552],
       [ 0.06896552,  0.13793103,  0.34482759, -0.17241379],
       [ 0.03448276,  0.06896552,  0.17241379,  0.4137931 ]])