<a href="https://colab.research.google.com/github/pouya-parsa/MME/blob/master/2/2_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rank of Matrix

- rank: maximum number of linearly independent column vectors
 - number of linearly independent row vectors.

- An outer product matrix xy T , where x and y are vectors in R n ,
has rank 1, proof:
 - ![proof!](https://drive.google.com/u/0/uc?id=1EAMlwCCup1ucv7bv_06o0QoAeVdvM_HO&export=download)

- Nonsingular Matrix: A N*N square matrix with rank = N that has an inverse matrix A^-1 which satisfies:
 - ![alt text](https://drive.google.com/u/0/uc?id=1xue6He6k65-v8PHIbLXGnbTFzkai-NH9)
  -If we multiply linearly independent vectors by a nonsingular matrix, then the
vectors remain linearly independent.


In [0]:
import numpy as np

In [5]:
mat_1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
np.linalg.matrix_rank(mat_1)

2

In [8]:
mat_2 = np.eye(3)
print(np.linalg.matrix_rank(mat_2))
print(mat_2)

3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
